image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  BUILD_CONTAINER_IMAGE: $CI_REGISTRY/kaplan2539/baumeister

before_script:
  - apk update && apk add coreutils
  - echo "NPROC=$(( 2 * $(nproc) ))"
  - echo "CI_REGISTRY=$CI_REGISTRY"
  - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
  - echo "CI_PROJECT_URL=$CI_PROJECT_URL"
  - echo "BUILD_CONTAINER_IMAGE=$BUILD_CONTAINER_IMAGE"

build:
  stage: build
  script:
    - mkdir -p artifacts/boot/dtbs
    - mkdir -p artifacts/usr
    - mkdir -p artifacts/deb
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $BUILD_CONTAINER_IMAGE
    - docker run --rm -v $PWD:/build -w /build $BUILD_CONTAINER_IMAGE ./build.sh
  artifacts:
    paths:
      - artifacts/
